version: 2
updates:
  - package-ecosystem: pip
    directory: "/bot"
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
    labels:
      - bot
  - package-ecosystem: docker
    directory: "/events"
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
    labels:
      - events
  - package-ecosystem: docker
    directory: "/bot"
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
    labels:
      - bot
  - package-ecosystem: pip
    directory: "/tools"
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
    labels:
      - tools
  - package-ecosystem: pip
    directory: "/events"
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
    labels:
      - events
